; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "TranscriptoHub"
#define MyAppVersion "1.1.0"
#define MyAppPublisher "Universidad Cooperativa de Colombia"
#define MyAppURL "https://ucc.edu.co/"
#define MyAppExeName "TranscriptoHub.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{52843853-05F1-4779-9E8C-115FBFCA8BEF}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={userappdata}\Universidad Cooperativa de Colombia\{#MyAppName}
PrivilegesRequired=admin
DisableDirPage=yes
SetupIconFile=D:\projects_ucc\proyecto_transcriptomica\assets\app.ico
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputBaseFilename=TranscriptoSetup
SolidCompression=yes
WizardStyle=modern

RestartIfNeededByRun=yes
SetupLogging=yes
OutputDir=./

[Languages]
Name: "spanish"; MessagesFile: "compiler:Languages\Spanish.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked; Check: not GetResume();

[Files]
; Ejecutable principal
Source: "D:\projects_ucc\proyecto_transcriptomica\dist\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion; Check: not GetResume();

; FastQC
Source: "D:\projects_ucc\proyecto_transcriptomica\programs\fastqc\*"; DestDir: "{app}\Programs\FastQC"; Flags: recursesubdirs createallsubdirs ignoreversion; Check: not GetResume();

; Trimmomatic
Source: "D:\projects_ucc\proyecto_transcriptomica\programs\trimmomatic\*"; DestDir: "{app}\Programs\Trimmomatic"; Flags: recursesubdirs createallsubdirs ignoreversion; Check: not GetResume();

; SortMeRNA
Source: "D:\projects_ucc\proyecto_transcriptomica\programs\sortmerna\*"; DestDir: "{app}\Programs\SortMeRNA"; Flags: recursesubdirs createallsubdirs ignoreversion; Check: not GetResume();

; Java
Source: "D:\projects_ucc\proyecto_transcriptomica\programs\java\jre-8u451-windows-x64.exe"; DestDir: "{tmp}"; Flags: deleteafterinstall; Check: not GetResume();

; Kraken2 & Krona
Source: "C:\Users\Alexander\OneDrive - Universidad Cooperativa de Colombia\proyecto_software_de_analisis_de_transcriptomica\installer\auto_kraken\import_debian_kraken_krona.ps1"; DestDir: "{tmp}"; Flags: deleteafterinstall; Check: GetResume();
Source: "C:\Users\Alexander\OneDrive - Universidad Cooperativa de Colombia\proyecto_software_de_analisis_de_transcriptomica\installer\DebianKrakenKrona.tar"; DestDir: "{tmp}"; Flags: deleteafterinstall; Check: GetResume();

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Check: not GetResume();
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon; Check: not GetResume();

[Run]
; 1) Instalación de Java
Filename: "{tmp}\jre-8u451-windows-x64.exe"; \
Parameters: "REBOOT=Suppress"; \
StatusMsg: "Instalando Java..."; \
Flags: waituntilterminated; \
Check: not GetResume();

; 2) Habilitar VirtualMachinePlatform
Filename: "cmd.exe"; \
Parameters: "/C dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart"; \
Flags: runhidden waituntilterminated; \
StatusMsg: "Habilitando Virtual Machine Platform Feature..."; \
Check: not GetResume();

; 3) Habilitar Hyper V
Filename: "cmd.exe"; \
Parameters: "/C dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart"; \
Flags: runhidden waituntilterminated; \
StatusMsg: "Habilitando Hyper V Feature..."; \
Check: not GetResume();

; 4) Habilitar WSL2
Filename: "cmd.exe"; \
Parameters: "/C dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart"; \
Flags: runhidden waituntilterminated; \
StatusMsg: "Habilitando Microsoft Windows Subsystem Linux Feature..."; \
Check: not GetResume();

; 5) Import Ubuntu
Filename: "{sys}\WindowsPowerShell\v1.0\powershell.exe"; \
Parameters: "-ExecutionPolicy Bypass -NoProfile -WindowStyle Hidden -File ""{tmp}\import_debian_kraken_krona.ps1"" ""{tmp}\DebianKrakenKrona.tar"" ""{sd}\WSL\DebianKrakenKrona"" ""{app}"""; \
StatusMsg: "Instalando Kraken2 | Importando Ubuntu con kraken2..."; \
Flags: runhidden waituntilterminated; \
Check: GetResume();

; 6) Instalación de software
Filename: "{app}\{#MyAppExeName}"; \
Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; \
Flags: nowait postinstall skipifsilent; \
Check: GetResume();

[Code]

{ Resume Mode }

var
  isResume: Boolean;

function CheckResume(): Boolean;
begin
  Result := CompareText(ExpandConstant('{param:resume}'), '1') = 0;
end;

function GetResume(): Boolean;
begin
  Result := isResume;
end;

function Restart(): Boolean;
var
  Cmd: String;
begin
  Cmd := '"' + ExpandConstant('{srcexe}') + '" /resume=1';
  RegWriteStringValue(HKCU, 'Software\Microsoft\Windows\CurrentVersion\RunOnce', 'TranscriptoHub_ContinueInstall', Cmd);
  Result := True;
end;

procedure RestartClick(Sender: TObject);
var
  Cmd: String;
  ResultCode: Integer;
begin
  Cmd := '"' + ExpandConstant('{srcexe}') + '" /resume=1';
  RegWriteStringValue(HKCU, 'Software\Microsoft\Windows\CurrentVersion\RunOnce', 'TranscriptoHub_ContinueInstall', Cmd);
  Exec('shutdown.exe', '-r -t 5 -c "Reiniciando para completar la instalación..."', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
end;

{  }

function ShouldSkipPage(PageID: Integer): Boolean;
begin
  Result := False;
  
  if isResume then
  begin
    if PageIndexFromID(PageID) < PageIndexFromID(wpReady) then Result := True;
  end;
end;

procedure CurPageChanged(CurPageID: Integer);
begin

  case CurPageID of
    wpReady:
    begin
      if isResume then
      begin
        WizardForm.NextButton.Caption := 'Continuar';
      end;
    end;
    wpFinished:
    begin
      if not isResume then
      begin
        WizardForm.NextButton.Caption := 'Reiniciar';
        WizardForm.NextButton.OnClick := @RestartClick;
      end;
    end;
  end;
end;

function InitializeSetup: Boolean;
begin
  isResume := CheckResume();
  Result := True
end;